WMS ID#11441
oracle-livelabs/security pull request #105
Opened 2023-07-10 09:36 UTC by gautamm2707

# Add here your ID#11441 

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-07-10 16:08 UTC, aberinnj commented
Hi,

Please make sure the filenames (the images) are **descriptive**

Thank you

2023-07-10 18:23 UTC, aberinnj requested changes

2023-07-10 18:23 UTC, aberinnj commented on linux-pam-sssd-identity-domains/add-sso-policy/images/image1.png
Please make sure the filenames are descriptive as mentioned in the self-QA doc

2023-07-10 19:37 UTC, gautamm2707 commented on linux-pam-sssd-identity-domains/add-sso-policy/images/image1.png
made changes in each image's description. kindly validate and confirm

2023-07-10 19:40 UTC, gautamm2707 commented on linux-pam-sssd-identity-domains/add-sso-policy/images/image1.png
Note: changes have been made in the description of the images (visible once you hover them on the screen) in the md files. 
No changes made on the "name" of the image files, as that does not makes sense; Kindly validate and confirm

2023-07-10 21:58 UTC, aberinnj commented on linux-pam-sssd-identity-domains/add-sso-policy/images/image1.png
Hi, the names of the images are exactly what I was referring to, it is in the self-QA doc

2023-07-11 10:14 UTC, gautamm2707 commented on linux-pam-sssd-identity-domains/add-sso-policy/images/image1.png
Hi ,the image names have been updated with more descriptive names. Kindly validate and merge.

2023-07-11 17:53 UTC, aberinnj approved these changes

2023-07-11 17:54 UTC, aberinnj approved these changes

2023-07-11 17:54 UTC, aberinnj commented
The rest lgtm!

I noticed that the workshop outline on WMS are not updated, please update it and I'll merge

2023-07-11 18:58 UTC, merged