WMS ID: 11315 and WMS ID: 11496
oracle-livelabs/security pull request #167
Opened 2024-02-21 15:34 UTC by ibalasun

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2024-02-21 17:47 UTC, ramumg commented
Hi @ibalasun, 

Please make a pull request per WMS. 

Thank you!

2024-02-22 12:19 UTC, ibalasun commented
Hi @ramumg ,

Updated. 

Thank you!

2024-02-22 13:23 UTC, denisemyrick commented
Hi @ibalasun, please update branch. It's out of date with base. Thanks!

2024-02-22 13:43 UTC, denisemyrick requested changes

2024-02-22 13:43 UTC, denisemyrick commented on accessgovernancee2e/create-campaign/images/Screenshot 2024-02-20 at 11.40.17 AM.png
Under create-changes you have a Screenshot image. File names need to be lowercase and that one needs to be renamed something more descriptive.

2024-02-22 13:43 UTC, denisemyrick commented on accessgovernance-access-controls/aginstance-cleanup/aginstance-cleanup.md
Prerequisites is a requirement for all labs.

2024-02-22 13:43 UTC, denisemyrick commented on accessgovernancee2e/aginstance-cleanup/aginstance-cleanup.md
All labs must have prerequisites

2024-02-22 13:43 UTC, denisemyrick commented on accessgovernancee2e/create-campaign/create-campaign.md
While reviewing I noticed you're a little inconsistent with bolding next

2024-02-22 13:43 UTC, denisemyrick commented on accessgovernancee2e/deploying-using-terraform/deploying-using-terraform.md
Needs prerequisites

2024-02-23 09:21 UTC, closed without merging

2024-02-23 09:42 UTC, ibalasun commented on accessgovernancee2e/deploying-using-terraform/deploying-using-terraform.md
Hi @denisemyrick ,

Closing this pull request. Will create a new one with the updated changes. Thanks