WMS ID: 3262
oracle-livelabs/security pull request #263
Opened 2024-11-15 00:02 UTC by kjlsinghoracle

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x ] All filenames are lower case (including folders, images, files, etc.)
- [ x ] Filenames are descriptive
- [ x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ x ] Image references in markdown contain an alternate text

2024-11-15 13:37 UTC, anacoman11 requested changes
Hi @kjlsinghoracle, please blur the private information from: 

- database/advanced/data-masking-subsetting-TTT24/images/update_ssh_creds-3.png
- database/advanced/data-masking-subsetting-TTT24/images/ssh-key-gen.png
- database/advanced/data-masking-subsetting-TTT24/images/dms-203.png

Please use lowercase for the names of these images:
- database/advanced/data-masking-subsetting-TTT24/images/DMS-110.png
- database/advanced/data-masking-subsetting-TTT24/images/DMS-111.png
- database/advanced/data-masking-subsetting/images/DMS-110.png
- database/advanced/data-masking-subsetting/images/DMS-111.png

Sent you a DM

2024-11-15 18:05 UTC, kjlsinghoracle commented
Images are not used in the markdown for [data-masking-subsetting-TTT24 so I have deleted them from images folder.

2024-11-15 18:17 UTC, kjlsinghoracle commented
Thanks for pointing it out. I just renamed it in both the image folders.

2024-11-16 04:37 UTC, anacoman11 approved these changes

2024-11-16 04:37 UTC, merged